

export const links = [
  {
    title: 'Витрина книг',
    active: true,
    link: '/',
    id: 1,
    testId: 'navigation-showcase',
    testIdBoorger: 'burger-showcase',
    sectionsBooks: [
      {
        subSectionsBooks: 'Все книгии',
        count: null,
        active: true,
        subLink: 'all',
        testId: 'navigation-books',
        testIdBoorger: 'burger-books',
      },
      {
        subSectionsBooks: 'Бизнес-книги',
        count: 14,
        active: false,
        subLink: 'business',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Детективы',
        count: 8,
        active: false,
        subLink: 'detective',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Детские книги',
        count: 14,
        active: false,
        subLink: 'children',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Зарубежная литература',
        count: 2,
        active: false,
        subLink: 'foreign',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'История',
        count: 5,
        active: false,
        subLink: 'history',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Классическая литература',
        count: 12,
        active: false,
        subLink: 'classic',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Книги по психологии',
        count: 11,
        active: false,
        subLink: 'psyhology',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Компьютерная литература',
        count: 54,
        active: false,
        subLink: 'computer',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Культура и искусство',
        count: 5,
        active: false,
        subLink: 'culture',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Наука и образование',
        count: 2,
        active: false,
        subLink: 'science',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Публицистическая литература ',
        count: 0,
        active: false,
        subLink: 'journalistic',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Справочники',
        count: 10,
        active: false,
        subLink: 'reference',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Фантастика',
        count: 2,
        active: false,
        subLink: 'fantasy',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Юмористическая литература',
        count: 0,
        active: false,
        subLink: 'humor',
        testId: null,
        testIdBoorger: '',
      },
    ],
  },
  {
    title: 'Правила пользования',
    active: false,
    link: '/rules',
    id: 2,
    testId: 'navigation-terms',
    testIdBoorger: 'burger-terms',
    sectionsBooks: [],
  },
  {
    title: 'Договор оферты',
    active: false,
    link: '/contract',
    id: 3,
    testId: 'navigation-contract',
    testIdBoorger: 'burger-contract',
    sectionsBooks: [],
  },
];
